// Auto-generated by scripts/generate-partner-data.mjs from public/partners/*.png filenames.
// Refine sector / reach / instagram / related manually as Henrique provides metadata.

export type PartnerSector =
  | 'beleza'
  | 'saude'
  | 'educacao'
  | 'gastronomia'
  | 'servicos'
  | 'moda'
  | 'tech'
  | 'outro'

export interface Partner {
  id: string
  name: string
  instagram?: string
  sector: PartnerSector
  reach: 1 | 2 | 3 | 4 | 5
  logo: string
  related?: string[]
}

export const SHOW_CONSTELLATION_LINES = false

export const partners: Partner[] = [
  {
    "id": "adegas-vinas",
    "name": "Adegas Vinas",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-adegas-vinas-200x120.png"
  },
  {
    "id": "amor-e-consciencia",
    "name": "Amor E Consciencia",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-amor-e-consciencia-200x120.png"
  },
  {
    "id": "bela-clean",
    "name": "Bela Clean",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-bela-clean-200x120.png"
  },
  {
    "id": "criativus-novo",
    "name": "Criativus Novo",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-criativus-novo-200x120.png"
  },
  {
    "id": "desafio",
    "name": "Desafio",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-desafio-200x120.png"
  },
  {
    "id": "domicio",
    "name": "Domicio",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-domicio-200x120.png"
  },
  {
    "id": "gavion",
    "name": "Gavion",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-gavion-200x120.png"
  },
  {
    "id": "kumon",
    "name": "Kumon",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-KUMON-200x120.png"
  },
  {
    "id": "leuck",
    "name": "Leuck",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-LEUCK-200x120.png"
  },
  {
    "id": "lumbieri",
    "name": "Lumbieri",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-lumbieri-200x120.png"
  },
  {
    "id": "midia-na-mesa",
    "name": "Midia Na Mesa",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-midia-na-mesa-200x120.png"
  },
  {
    "id": "mistyura",
    "name": "Mistyura",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-mistyura-200x120.png"
  },
  {
    "id": "nova-era",
    "name": "Nova Era",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-nova-era-200x120.png"
  },
  {
    "id": "posseg",
    "name": "Posseg",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-posseg-200x120.png"
  },
  {
    "id": "regiane",
    "name": "Regiane",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-regiane-200x120.png"
  },
  {
    "id": "sos-canos-info",
    "name": "Sos Canos Info",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-sos-canos-info-200x120.png"
  },
  {
    "id": "tenax",
    "name": "Tenax",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-tenax-200x120.png"
  },
  {
    "id": "toca-do-pao",
    "name": "Toca Do Pao",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site-toca-do-pao-200x120.png"
  },
  {
    "id": "360",
    "name": "360",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-360-200x120.png"
  },
  {
    "id": "alinesantosnutri",
    "name": "Alinesantosnutri",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-ALINESANTOSNUTRI-200x120.png"
  },
  {
    "id": "andressa",
    "name": "Andressa",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-andressa-200x120.png"
  },
  {
    "id": "baby-200x119png",
    "name": "Baby 200x119.Png",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-baby-200x119.png"
  },
  {
    "id": "cibele",
    "name": "Cibele",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-cibele-200x120.png"
  },
  {
    "id": "ciclojoel",
    "name": "Ciclojoel",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-ciclojoel-200x120.png"
  },
  {
    "id": "consertos-express",
    "name": "Consertos Express",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-consertos-express-200x120.png"
  },
  {
    "id": "cressol",
    "name": "Cressol",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-cressol-200x120.png"
  },
  {
    "id": "doce-amargo",
    "name": "Doce Amargo",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-doce-amargo-200x120.png"
  },
  {
    "id": "doterra",
    "name": "Doterra",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-doterra-200x120.png"
  },
  {
    "id": "flores-patricia-consorcios",
    "name": "Flores Patricia Consorcios",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-flores-patricia-consorcios-200x120.png"
  },
  {
    "id": "fly",
    "name": "Fly",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-fly-200x120.png"
  },
  {
    "id": "foco-personalizados",
    "name": "Foco Personalizados",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-foco-personalizados-200x120.png"
  },
  {
    "id": "guria",
    "name": "Guria",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-guria-200x120.png"
  },
  {
    "id": "mef-psico",
    "name": "Mef Psico",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-mef-psico-200x120.png"
  },
  {
    "id": "memoraveis",
    "name": "Memoraveis",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-memoraveis-200x120.png"
  },
  {
    "id": "mistura",
    "name": "Mistura",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-mistura-200x120.png"
  },
  {
    "id": "ms",
    "name": "Ms",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-ms-200x120.png"
  },
  {
    "id": "seibras",
    "name": "Seibras",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-seibras-200x120.png"
  },
  {
    "id": "zannata",
    "name": "Zannata",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-site1-zannata-200x120.png"
  },
  {
    "id": "gui-imoveis",
    "name": "Gui Imoveis",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/banners-sitegui-imoveis-200x120.png"
  },
  {
    "id": "abm",
    "name": "Abm",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-ABM-200x120.png"
  },
  {
    "id": "advogado",
    "name": "Advogado",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-advogado-200x120.png"
  },
  {
    "id": "andres",
    "name": "Andres",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-ANDRES-200x120.png"
  },
  {
    "id": "atitude",
    "name": "Atitude",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-atitude-200x120.png"
  },
  {
    "id": "ativa",
    "name": "Ativa",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-ATIVA-200x120.png"
  },
  {
    "id": "ballons",
    "name": "Ballons",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-ballons-v2-200x120.png"
  },
  {
    "id": "bendita",
    "name": "Bendita",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-BENDITA-200x120.png"
  },
  {
    "id": "cintia-mendes",
    "name": "Cintia Mendes",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-cintia-mendes-200x120.png"
  },
  {
    "id": "clinica-schaff",
    "name": "Clinica Schaff",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-CLINICA-SCHAFF-200x120.png"
  },
  {
    "id": "di-tour",
    "name": "Di Tour",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-di-tour-200x120.png"
  },
  {
    "id": "dm",
    "name": "Dm",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-dm-200x120.png"
  },
  {
    "id": "essentis",
    "name": "Essentis",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-essentis-200x120.png"
  },
  {
    "id": "evelin",
    "name": "Evelin",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-EVELIN-200x120.png"
  },
  {
    "id": "executiva-1",
    "name": "Executiva 1",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-executiva-1-200x120.png"
  },
  {
    "id": "fire",
    "name": "Fire",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-fire-200x120.png"
  },
  {
    "id": "flor-e-ser",
    "name": "Flor E Ser",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-flor-e-ser-200x120.png"
  },
  {
    "id": "fraga",
    "name": "Fraga",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-fraga-200x120.png"
  },
  {
    "id": "iconstru",
    "name": "Iconstru",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-iconstru-200x120.png"
  },
  {
    "id": "inova",
    "name": "Inova",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-inova-200x120.png"
  },
  {
    "id": "jaque",
    "name": "Jaque",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-jaque-200x120.png"
  },
  {
    "id": "juliana",
    "name": "Juliana",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-juliana-200x120.png"
  },
  {
    "id": "karam-adv",
    "name": "Karam Adv",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-karam-adv-200x120.png"
  },
  {
    "id": "la-rosa",
    "name": "La Rosa",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-la-rosa-200x120.png"
  },
  {
    "id": "lemali",
    "name": "Lemali",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-lemali-200x120.png"
  },
  {
    "id": "liarche",
    "name": "Liarche",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-LIARCHE-200x120.png"
  },
  {
    "id": "lidiane-avila",
    "name": "Lidiane Avila",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-lidiane-avila-200x120.png"
  },
  {
    "id": "luna",
    "name": "Luna",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-LUNA-200x120.png"
  },
  {
    "id": "nexx",
    "name": "Nexx",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-nexx-200x120.png"
  },
  {
    "id": "noca",
    "name": "Noca",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-noca-200x120.png"
  },
  {
    "id": "nucleo",
    "name": "Nucleo",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-NUCLEO-200x120.png"
  },
  {
    "id": "organizacao",
    "name": "Organizacao",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-ORGANIZACAO-200x120.png"
  },
  {
    "id": "paola",
    "name": "Paola",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-PAOLA-200x120.png"
  },
  {
    "id": "pimenta",
    "name": "Pimenta",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-pimenta-200x120.png"
  },
  {
    "id": "raupp",
    "name": "Raupp",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-raupp-200x120.png"
  },
  {
    "id": "rhf",
    "name": "Rhf",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-rhf-200x120.png"
  },
  {
    "id": "rocsana",
    "name": "Rocsana",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-rocsana-200x120.png"
  },
  {
    "id": "s2",
    "name": "S2",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-s2-200x120.png"
  },
  {
    "id": "sandra",
    "name": "Sandra",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-sandra-200x120.png"
  },
  {
    "id": "sheila",
    "name": "Sheila",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-SHEILA-200x120.png"
  },
  {
    "id": "superfantastico",
    "name": "Superfantastico",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-superfantastico-200x120.png"
  },
  {
    "id": "suzana-nagel",
    "name": "Suzana Nagel",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-suzana-nagel-200x120.png"
  },
  {
    "id": "vip-place",
    "name": "Vip Place",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-vip-place-200x120.png"
  },
  {
    "id": "zls",
    "name": "Zls",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/LOGOS-SITE-zls-200x120.png"
  },
  {
    "id": "preto-renatta-200x96png",
    "name": "Preto Renatta 200x96.Png",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/preto-renatta-200x96.png"
  },
  {
    "id": "sem-titulo-1-200x81png",
    "name": "Sem Titulo 1 200x81.Png",
    "sector": "outro",
    "reach": 3,
    "logo": "/partners/Sem-titulo-1-200x81.png"
  }
]
